=== InveO/SharePlot/SharePlot/xml/tables/table2.dtd
<!--
// @Title			Table.dtd 
// @Version			2.0
// @Author			Melinda Gentizon
// @Company		Yellow-B
// @Description		Definition of the database tables
//
-->
<!--
Generic Column Types in Java Enabling Tool:
  name 			is the unique name of this generic column type
  type 			the type of the column
  dbtype 		the SQL type of the column
  length		the length of the column
  nullable		Boolean value, if true indicates the column can hold null values
-->
<!ATTLIST TYPE
	name ID #REQUIRED
	type CDATA #REQUIRED
	dbtype CDATA ""
	length CDATA ""
	nullable (true | false) "true"
>
<!ELEMENT TYPE EMPTY>
<!ELEMENT GENERIC (TYPE)*>
<!--
Column of a table:
  name is used to refer to this COLUMN in the Java Enabling Tool.
  implements		the name of the generic column type, that is referenced by this column
  type 			the type of the column
  dbtype 		the SQL type of the column
  length			the length of the column
  nullable		Boolean value, if true indicates the column can hold null values
-->
<!ATTLIST COLUMN
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	length CDATA #IMPLIED
	nullable (true | false) "true"
    autoincrement (true | false) "false"
>
<!ELEMENT COLUMN EMPTY>
<!--
The component that compose a primary key of a table.
-->
<!ATTLIST KEYITEM
	component CDATA #REQUIRED
>
<!ELEMENT KEYITEM EMPTY>
<!ELEMENT PRIMARYKEY (KEYITEM+)>
<!--
A database table:
   name         is the name of the table inside the Java Enabling Tool (used i.e. in MAPPING element). 
-->
<!ATTLIST TABLE
	name CDATA #REQUIRED
>
<!ELEMENT TABLE (COLUMN*, PRIMARYKEY)>
<!--
A view:
   name         is the name of the view inside the Java Enabling Tool (used i.e. in MAPPING element). 
   sql          is the SQL command that defines the view.
-->
<!ATTLIST VIEW
	name CDATA #REQUIRED
	sql CDATA ""
>
<!ELEMENT VIEW (COLUMN*, PRIMARYKEY?)>
<!ELEMENT TABLES (GENERIC*, (VIEW | TABLE)*)>

=== InveO/SharePlot/SharePlot/xml/tables/Tables.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TABLES SYSTEM "table2.dtd">
<!-- 
    Warning : The Column name must match the name of the field in the java classes

-->
<TABLES>
    <TABLE name="Portfolio">
        <COLUMN name="idPortfolio" type="Long" length="10" nullable="false" autoincrement="true" />
        <COLUMN name="isFake" type="String" length="1" nullable="false" autoincrement="false" />
        <COLUMN name="name" type="String" length="45" nullable="false" autoincrement="false" />
        <PRIMARYKEY>
            <KEYITEM component="idPortfolio"/>
        </PRIMARYKEY>
    </TABLE>
    <TABLE name="ShareQuantity">
        <COLUMN name="idShareQuantity" type="Long" length="10" nullable="false" autoincrement="true" />
        <COLUMN name="changeFee" type="java.math.BigDecimal" length="12" nullable="false" autoincrement="false" />
        <COLUMN name="changeQuantity" type="java.math.BigDecimal" length="12" nullable="false" autoincrement="false" />
        <COLUMN name="changeType" type="String" length="1" nullable="false" autoincrement="false" />
        <COLUMN name="changeValue" type="java.math.BigDecimal" length="12" nullable="false" autoincrement="false" />
        <COLUMN name="description" type="String" length="1000" nullable="true" autoincrement="false" />
        <COLUMN name="idShare" type="Long" length="10" nullable="false" autoincrement="false" />
        <COLUMN name="valueDate" type="java.util.Date" length="10" nullable="false" autoincrement="false" />
        <PRIMARYKEY>
            <KEYITEM component="idShareQuantity"/>
        </PRIMARYKEY>
    </TABLE>
    <TABLE name="Share">
        <COLUMN name="idShare" type="Long" length="10" nullable="false" autoincrement="true" />
        <COLUMN name="codeISIN" type="String" length="45" nullable="true" autoincrement="false" />
        <COLUMN name="codeYahoo" type="String" length="45" nullable="true" autoincrement="false" />
        <COLUMN name="description" type="String" length="4000" nullable="true" autoincrement="false" />
        <COLUMN name="idPortfolio" type="Long" length="10" nullable="false" autoincrement="false" />
        <COLUMN name="name" type="String" length="255" nullable="false" autoincrement="false" />
        <PRIMARYKEY>
            <KEYITEM component="idShare"/>
        </PRIMARYKEY>
    </TABLE>
    <TABLE name="ShareValue">
        <COLUMN name="idShareValue" type="Long" length="10" nullable="false" autoincrement="true" />
        <COLUMN name="isShare" type="Long" length="10" nullable="false" autoincrement="false" />
        <COLUMN name="value" type="java.math.BigDecimal" length="10" nullable="false" autoincrement="false" />
        <COLUMN name="valueDate" type="java.util.Date" length="10" nullable="false" autoincrement="false" />
        <PRIMARYKEY>
            <KEYITEM component="idShareValue"/>
        </PRIMARYKEY>
    </TABLE>
</TABLES>
