=== InveO/SharePlot/SharePlot/xml/metadata/ejb/component.dtd
<!ATTLIST METHOD
    name CDATA #REQUIRED
>
<!ELEMENT METHOD EMPTY>
<!ATTLIST TRANSACTION
    type (Required | NotSupported | RequiresNew | Support | Mandatory | Never) "Required"
>
<!ELEMENT TRANSACTION (METHOD*)>
<!ATTLIST FINDERBODY
    type (sql | nosql) "nosql"
    sql_string CDATA ""
    buffersize CDATA ""
>
<!ELEMENT FINDERBODY EMPTY>
<!ATTLIST INPUT
    name CDATA #REQUIRED
    type CDATA #REQUIRED
>
<!ELEMENT INPUT EMPTY>
<!ATTLIST FINDER
    name CDATA #REQUIRED
    default (true | false) "false"
>
<!ELEMENT FINDER (INPUT*, FINDERBODY)>
<!ATTLIST COLUMN
    name CDATA #REQUIRED
    localname CDATA #REQUIRED
    paramName CDATA #REQUIRED
    type CDATA #REQUIRED
    dbtype (VARCHAR | VARCHAR2 | DATE | INTEGER | DOUBLE | CHAR | SMALLINT | TIMESTAMP | TIME | REAL | BIGINT | BIT | OBJECT | DECIMAL | BLOB ) "VARCHAR"
    length CDATA ""
    noOfDecimal CDATA ""
    nullable (true | false) "false"
    autoIncrement (true | false) "false"
    default CDATA ""
>
<!ELEMENT COLUMN EMPTY>
<!ATTLIST FKITEM
    column CDATA #REQUIRED
    foreigncolumn CDATA #REQUIRED
    foreigncolumnlocalname CDATA #REQUIRED
>
<!ELEMENT FKITEM EMPTY>
<!ATTLIST FOREIGNKEY
    name CDATA #REQUIRED
    foreigntable CDATA #REQUIRED
    foreigntablelocalname CDATA #REQUIRED
>
<!ELEMENT FOREIGNKEY (FKITEM+)>
<!ATTLIST KEYITEM
    component CDATA #REQUIRED
    paramName CDATA #REQUIRED
    type CDATA #REQUIRED
>
<!ELEMENT KEYITEM EMPTY>
<!ELEMENT PRIMARYKEY (KEYITEM+)>
<!ATTLIST TABLE
    name CDATA #REQUIRED
    localname CDATA #REQUIRED
    virtuel (true | false) "false"
>
<!ELEMENT TABLE (COLUMN*, PRIMARYKEY, FOREIGNKEY*)>
<!ATTLIST BEANDEF
    name CDATA #REQUIRED
    ejbtype (entity | session) "entity"
    package CDATA #REQUIRED
    home CDATA #REQUIRED
    remote CDATA #REQUIRED
    ejbclass CDATA #REQUIRED
    primkeyclass CDATA ""
    persistence-type (Container | Bean) "Container"
    session-type (Stateful | Stateless) "Stateful"
>
<!ELEMENT BEANDEF EMPTY>
<!ATTLIST COMPONENT
    name CDATA #REQUIRED
    descriptif CDATA ""
    projetName CDATA #REQUIRED
>
<!ELEMENT COMPONENT (BEANDEF+, TABLE+, FINDER*, TRANSACTION*)>

=== InveO/SharePlot/SharePlot/xml/metadata/ejb/ShareValue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMPONENT SYSTEM "component.dtd">
<!-- The COMPONENT xml files are used by various tools to generate CMP entity beans
    and some related configuration files.

    Generated by JetTools, do not edit this file directly.
    
    projetName : name of the project these descriptors are part of
    name : name of the component, not used for the moment -->
<COMPONENT projetName="SharePlot" name="ShareValue">
    
    <!-- BEANDEF : define the EJB specific information
        name : Name of the EJB
        persistence-type : Type of the EJB persistence mechanism, this may be Container, Bean
        ejbtype : Type of the EJB, this may be entity or session
        package : java package the EJB classes are to be created in
        ejbclass : name of the bean implementation class
        primkeyclass : name of the class to use as the PK object, in the case of an autoincremented key this must be java.lang.Object
        remote : name of the remote interface
        home : name of the home interface
    -->
    <BEANDEF name="ShareValue" 
        persistence-type="Container" 
        ejbtype="entity" 
        package="jet.shareplot.persistence.ejb.sharevalue" 
        ejbclass="ShareValueBean" 
        primkeyclass="java.lang.Object"
        remote="ShareValueRemote" 
        home="ShareValueHome"/>
    
    <!-- TABLE : describes the table this bean corresponds to
        name : name of the table in the database -->
    <TABLE name="ShareValue" localname="ShareValue">
        
        <!-- COLUMN : Describes a column in the table
            paramName : name to use for this column in the java classes 
            type : java type to use
            name : name of the column in the table
            dbtype : SQL type in the DB
            length : length in DB 
            noOfDecimal : number of decimal points (if appropriate)
            nullable : "true" if the column accepts null values
            autoIncrement : "true" if the column is flagged as auto-increment in the DB
            -->
        <COLUMN paramName="idShareValue" type="Long" name="idShareValue" localname="idShareValue" dbtype="INTEGER" length="10" noOfDecimal="0" nullable="false" autoIncrement="true" />
        <COLUMN paramName="idShare" type="Long" name="idShare" localname="idShare" dbtype="INTEGER" length="10" noOfDecimal="0" nullable="false" autoIncrement="false" />
        <COLUMN paramName="valueDate" type="java.util.Date" name="valueDate" localname="valueDate" dbtype="DATE" length="10" noOfDecimal="0" nullable="false" autoIncrement="false" />
        <COLUMN paramName="value" type="java.math.BigDecimal" name="value" localname="value" dbtype="DECIMAL" length="10" noOfDecimal="2" nullable="false" autoIncrement="false" />
        
        <!-- PRIMARYKEY : identifies the columns to use as primary key -->
        <PRIMARYKEY>
            <!-- KEYITEM : item of the PK
                component : name of the corresponding column
                type : java type to use
                paramName : name to use in the java classes -->
            <KEYITEM component="idShareValue" type="Long" paramName="idShareValue"/>
        </PRIMARYKEY>
        
        <!-- FOREIGNKEY : identifies the columns to use as foreign key -->
        <FOREIGNKEY name="fk_ShareValue_Share" foreigntable="Share" foreigntablelocalname="Share" >
            <FKITEM column="idShare" foreigncolumn="idShare" foreigncolumnlocalname="idShare" />
        </FOREIGNKEY>
        
    </TABLE>

    <!-- FINDER : This will define the list of finders that are to be generated
        default : not used
        name : name of the finder that is to be generated
     -->
        <!-- INPUT : defines an argument for the finder
            type : java type
            name : name to give the argument in the java classes -->
        <!-- FINDERBODY : 
            buffersize : not used
            sql_string : sql query string, this should always start with "where" 
            type : only "sql" is supported at the moment-->
    
    <!-- Define the transaction level for various methods -->
    <TRANSACTION type="Required">
        <METHOD name="remove"/>
    </TRANSACTION>
    <TRANSACTION type="Required">
        <METHOD name="create"/>
    </TRANSACTION>
    <TRANSACTION type="Required">
        <METHOD name="update"/>
    </TRANSACTION>
</COMPONENT>

=== InveO/SharePlot/SharePlot/xml/metadata/ejb/ShareQuantity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMPONENT SYSTEM "component.dtd">
<!-- The COMPONENT xml files are used by various tools to generate CMP entity beans
    and some related configuration files.

    Generated by JetTools, do not edit this file directly.
    
    projetName : name of the project these descriptors are part of
    name : name of the component, not used for the moment -->
<COMPONENT projetName="SharePlot" name="ShareQuantity">
    
    <!-- BEANDEF : define the EJB specific information
        name : Name of the EJB
        persistence-type : Type of the EJB persistence mechanism, this may be Container, Bean
        ejbtype : Type of the EJB, this may be entity or session
        package : java package the EJB classes are to be created in
        ejbclass : name of the bean implementation class
        primkeyclass : name of the class to use as the PK object, in the case of an autoincremented key this must be java.lang.Object
        remote : name of the remote interface
        home : name of the home interface
    -->
    <BEANDEF name="ShareQuantity" 
        persistence-type="Container" 
        ejbtype="entity" 
        package="jet.shareplot.persistence.ejb.sharequantity" 
        ejbclass="ShareQuantityBean" 
        primkeyclass="java.lang.Object"
        remote="ShareQuantityRemote" 
        home="ShareQuantityHome"/>
    
    <!-- TABLE : describes the table this bean corresponds to
        name : name of the table in the database -->
    <TABLE name="ShareQuantity" localname="ShareQuantity">
        
        <!-- COLUMN : Describes a column in the table
            paramName : name to use for this column in the java classes 
            type : java type to use
            name : name of the column in the table
            dbtype : SQL type in the DB
            length : length in DB 
            noOfDecimal : number of decimal points (if appropriate)
            nullable : "true" if the column accepts null values
            autoIncrement : "true" if the column is flagged as auto-increment in the DB
            -->
        <COLUMN paramName="idShareQuantity" type="Long" name="idShareQuantity" localname="idShareQuantity" dbtype="INTEGER" length="10" noOfDecimal="0" nullable="false" autoIncrement="true" />
        <COLUMN paramName="idShare" type="Long" name="idShare" localname="idShare" dbtype="INTEGER" length="10" noOfDecimal="0" nullable="false" autoIncrement="false" />
        <COLUMN paramName="valueDate" type="java.util.Date" name="valueDate" localname="valueDate" dbtype="DATE" length="10" noOfDecimal="0" nullable="false" autoIncrement="false" />
        <COLUMN paramName="description" type="String" name="description" localname="description" dbtype="VARCHAR" length="1000" noOfDecimal="0" nullable="true" autoIncrement="false" />
        <COLUMN paramName="changeType" type="String" name="changeType" localname="changeType" dbtype="CHAR" length="1" noOfDecimal="0" nullable="false" autoIncrement="false" />
        <COLUMN paramName="changeValue" type="java.math.BigDecimal" name="changeValue" localname="changeValue" dbtype="DECIMAL" length="12" noOfDecimal="2" nullable="false" autoIncrement="false" />
        <COLUMN paramName="changeFee" type="java.math.BigDecimal" name="changeFee" localname="changeFee" dbtype="DECIMAL" length="12" noOfDecimal="2" nullable="false" autoIncrement="false" />
        <COLUMN paramName="changeQuantity" type="java.math.BigDecimal" name="changeQuantity" localname="changeQuantity" dbtype="DECIMAL" length="12" noOfDecimal="2" nullable="false" autoIncrement="false" />
        
        <!-- PRIMARYKEY : identifies the columns to use as primary key -->
        <PRIMARYKEY>
            <!-- KEYITEM : item of the PK
                component : name of the corresponding column
                type : java type to use
                paramName : name to use in the java classes -->
            <KEYITEM component="idShareQuantity" type="Long" paramName="idShareQuantity"/>
        </PRIMARYKEY>
        
        <!-- FOREIGNKEY : identifies the columns to use as foreign key -->
        <FOREIGNKEY name="fk_ShareQuantity_Share" foreigntable="Share" foreigntablelocalname="Share" >
            <FKITEM column="idShare" foreigncolumn="idShare" foreigncolumnlocalname="idShare" />
        </FOREIGNKEY>
        
    </TABLE>

    <!-- FINDER : This will define the list of finders that are to be generated
        default : not used
        name : name of the finder that is to be generated
     -->
        <!-- INPUT : defines an argument for the finder
            type : java type
            name : name to give the argument in the java classes -->
        <!-- FINDERBODY : 
            buffersize : not used
            sql_string : sql query string, this should always start with "where" 
            type : only "sql" is supported at the moment-->
    
    <!-- Define the transaction level for various methods -->
    <TRANSACTION type="Required">
        <METHOD name="remove"/>
    </TRANSACTION>
    <TRANSACTION type="Required">
        <METHOD name="create"/>
    </TRANSACTION>
    <TRANSACTION type="Required">
        <METHOD name="update"/>
    </TRANSACTION>
</COMPONENT>
