=== InveO/SharePlot/SharePlot/xml/META-INF/ejb.dtd
<!--
The ID mechanism is to allow tools that produce additional deployment
information (i.e information beyond the standard EJB deployment
descriptor information) to store the non-standard information in a
separate file, and easily refer from these tools-specific files to the
information in the standard deployment descriptor.
The EJB architecture does not allow the tools to add the non-standard
information into the EJB deployment descriptor.
-->
<!ATTLIST	assembly-descriptor		id	ID #IMPLIED>
<!ELEMENT	assembly-descriptor		(security-role*, method-permission*,container-transaction*)>
<!ATTLIST	cmp-field				id	ID #IMPLIED>
<!ELEMENT	cmp-field				(description?, field-name)>
<!ATTLIST	container-transaction	id	ID #IMPLIED>
<!ELEMENT	container-transaction	(description?, method+,trans-attribute)>
<!ATTLIST	description				id	ID #IMPLIED>
<!ELEMENT	description				(#PCDATA)>
<!ATTLIST	display-name			id	ID #IMPLIED>
<!ELEMENT	display-name			(#PCDATA)>
<!ATTLIST	ejb-class				id	ID #IMPLIED>
<!ELEMENT	ejb-class				(#PCDATA)>
<!ATTLIST	ejb-client-jar				id	ID #IMPLIED>
<!ELEMENT	ejb-client-jar				(#PCDATA)>
<!ATTLIST	ejb-jar					id	ID #IMPLIED>
<!ELEMENT	ejb-jar					(description?, display-name?, small-icon?,large-icon?, enterprise-beans, assembly-descriptor?,ejb-client-jar?)>
<!ATTLIST	ejb-link					id	ID #IMPLIED>
<!ELEMENT	ejb-link					(#PCDATA)>
<!ATTLIST	ejb-name				id	ID #IMPLIED>
<!ELEMENT	ejb-name				(#PCDATA)>
<!ATTLIST	ejb-ref					id	ID #IMPLIED>
<!ELEMENT	ejb-ref					(description?, ejb-ref-name, ejb-ref-type, home,remote, ejb-link?)>
<!ATTLIST	ejb-ref-name			id	ID #IMPLIED>
<!ELEMENT	ejb-ref-name			(#PCDATA)>
<!ATTLIST	ejb-ref-type				id	ID #IMPLIED>
<!ELEMENT	ejb-ref-type				(#PCDATA)>
<!ATTLIST	enterprise-beans		id	ID #IMPLIED>
<!ELEMENT	enterprise-beans		(session | entity)+>
<!ATTLIST	entity					id	ID #IMPLIED>
<!ELEMENT	entity					(description?, display-name?, small-icon?,large-icon?, ejb-name, home, remote, ejb-class, persistence-type, prim-key-class, reentrant, cmp-field*, primkey-field?, env-entry*, ejb-ref*, security-role-ref*, resource-ref*)>
<!ATTLIST	env-entry				id	ID #IMPLIED>
<!ELEMENT	env-entry				(description?, env-entry-name, env-entry-type,env-entry-value?)>
<!ATTLIST	env-entry-name			id	ID #IMPLIED>
<!ELEMENT	env-entry-name			(#PCDATA)>
<!ATTLIST	env-entry-type			id	ID #IMPLIED>
<!ELEMENT	env-entry-type			(#PCDATA)>
<!ATTLIST	env-entry-value			id	ID #IMPLIED>
<!ELEMENT	env-entry-value			(#PCDATA)>
<!ATTLIST	field-name				id	ID #IMPLIED>
<!ELEMENT	field-name				(#PCDATA)>
<!ATTLIST	home					id	ID #IMPLIED>
<!ELEMENT	home					(#PCDATA)>
<!ATTLIST	large-icon				id	ID #IMPLIED>
<!ELEMENT	large-icon				(#PCDATA)>
<!ATTLIST method					id	ID #IMPLIED>
<!ELEMENT	method					(description?, ejb-name, method-intf?, method-name,method-params?)>
<!ATTLIST	method-intf				id	ID #IMPLIED>
<!ELEMENT	method-intf				(#PCDATA)>
<!ATTLIST	method-name			id	ID #IMPLIED>
<!ELEMENT	method-name			(#PCDATA)>
<!ATTLIST	method-param			id	ID #IMPLIED>
<!ELEMENT	method-param			(#PCDATA)>
<!ATTLIST	method-params			id	ID #IMPLIED>
<!ELEMENT	method-params			(method-param*)>
<!ATTLIST	method-permission		id	ID #IMPLIED>
<!ELEMENT	method-permission		(description?, role-name+, method+)>
<!ATTLIST	persistence-type		id	ID #IMPLIED>
<!ELEMENT	persistence-type		(#PCDATA)>
<!ATTLIST	prim-key-class			id	ID #IMPLIED>
<!ELEMENT	prim-key-class			(#PCDATA)>
<!ATTLIST	primkey-field			id	ID #IMPLIED>
<!ELEMENT	primkey-field			(#PCDATA)>
<!ATTLIST	reentrant				id	ID #IMPLIED>
<!ELEMENT	reentrant				(#PCDATA)>
<!ATTLIST	remote					id	ID #IMPLIED>
<!ELEMENT	remote					(#PCDATA)>
<!ATTLIST	res-auth				id	ID #IMPLIED>
<!ELEMENT	res-auth				(#PCDATA)>
<!ATTLIST	res-ref-name			id	ID #IMPLIED>
<!ELEMENT	res-ref-name			(#PCDATA)>
<!ATTLIST	res-type				id	ID #IMPLIED>
<!ELEMENT	res-type				(#PCDATA)>
<!ATTLIST	resource-ref			id	ID #IMPLIED>
<!ELEMENT	resource-ref			(description?, res-ref-name, res-type,res-auth)>
<!ATTLIST	role-link					id	ID #IMPLIED>
<!ELEMENT	role-link					(#PCDATA)>
<!ATTLIST	role-name				id	ID #IMPLIED>
<!ELEMENT	role-name				(#PCDATA)>
<!ATTLIST	security-role			id	ID #IMPLIED>
<!ELEMENT	security-role			(description?, role-name)>
<!ATTLIST	security-role-ref			id	ID #IMPLIED>
<!ELEMENT	security-role-ref			(description?, role-name, role-link?)>
<!ATTLIST	session-type			id	ID #IMPLIED>
<!ELEMENT	session-type			(#PCDATA)>
<!ATTLIST	session					id	ID #IMPLIED>
<!ELEMENT	session					(description?, display-name?, small-icon?,large-icon?, ejb-name, home, remote, ejb-class,session-type, transaction-type, env-entry*,ejb-ref*, security-role-ref*, resource-ref*)>
<!ATTLIST	small-icon				id	ID #IMPLIED>
<!ELEMENT	small-icon				(#PCDATA)>
<!ATTLIST	transaction-type			id	ID #IMPLIED>
<!ELEMENT	transaction-type			(#PCDATA)>
<!ATTLIST	trans-attribute			id	ID #IMPLIED>
<!ELEMENT	trans-attribute			(#PCDATA)>

=== InveO/SharePlot/SharePlot/xml/META-INF/ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ejb-jar SYSTEM "ejb.dtd">
<ejb-jar>
    <description>JET Container </description>
    <display-name>Jet</display-name>
    <enterprise-beans>
        <entity>
            <display-name> EJB for ShareValue</display-name>
            <ejb-name>ShareValue</ejb-name>
            <home>jet.shareplot.persistence.ejb.sharevalue.ShareValueHome</home>
            <remote>jet.shareplot.persistence.ejb.sharevalue.ShareValueRemote</remote>
            <ejb-class>jet.shareplot.persistence.ejb.sharevalue.ShareValueBean</ejb-class>
            <persistence-type>Container</persistence-type>
            <prim-key-class>java.lang.Object</prim-key-class>
            <reentrant>True</reentrant>
            <cmp-field>
                <description> Desc for idShareValue</description>
                <field-name>idShareValue</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for isShare</description>
                <field-name>isShare</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for valueDate</description>
                <field-name>valueDate</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for value</description>
                <field-name>value</field-name>
            </cmp-field>
        </entity>
        <entity>
            <display-name> EJB for Share</display-name>
            <ejb-name>Share</ejb-name>
            <home>jet.shareplot.persistence.ejb.share.ShareHome</home>
            <remote>jet.shareplot.persistence.ejb.share.ShareRemote</remote>
            <ejb-class>jet.shareplot.persistence.ejb.share.ShareBean</ejb-class>
            <persistence-type>Container</persistence-type>
            <prim-key-class>java.lang.Object</prim-key-class>
            <reentrant>True</reentrant>
            <cmp-field>
                <description> Desc for idShare</description>
                <field-name>idShare</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for name</description>
                <field-name>name</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for description</description>
                <field-name>description</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for code</description>
                <field-name>code</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for datePurchase</description>
                <field-name>datePurchase</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for purchasePrice</description>
                <field-name>purchasePrice</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for entryFee</description>
                <field-name>entryFee</field-name>
            </cmp-field>
        </entity>
        <entity>
            <display-name> EJB for ShareQuantity</display-name>
            <ejb-name>ShareQuantity</ejb-name>
            <home>jet.shareplot.persistence.ejb.sharequantity.ShareQuantityHome</home>
            <remote>jet.shareplot.persistence.ejb.sharequantity.ShareQuantityRemote</remote>
            <ejb-class>jet.shareplot.persistence.ejb.sharequantity.ShareQuantityBean</ejb-class>
            <persistence-type>Container</persistence-type>
            <prim-key-class>java.lang.Object</prim-key-class>
            <reentrant>True</reentrant>
            <cmp-field>
                <description> Desc for idShareQuantity</description>
                <field-name>idShareQuantity</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for idShare</description>
                <field-name>idShare</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for valueDate</description>
                <field-name>valueDate</field-name>
            </cmp-field>
            <cmp-field>
                <description> Desc for changeType</description>
                <field-name>changeType</field-name>
            </cmp-field>
        </entity>
    </enterprise-beans>
    <assembly-descriptor>
        <container-transaction>
            <description> Desc for ShareValue</description>
            <method>
                <ejb-name>ShareValue</ejb-name>
                <method-name>*</method-name>
            </method>
            <trans-attribute>Required</trans-attribute>
        </container-transaction>
        <container-transaction>
            <description> Desc for Share</description>
            <method>
                <ejb-name>Share</ejb-name>
                <method-name>*</method-name>
            </method>
            <trans-attribute>Required</trans-attribute>
        </container-transaction>
        <container-transaction>
            <description> Desc for ShareQuantity</description>
            <method>
                <ejb-name>ShareQuantity</ejb-name>
                <method-name>*</method-name>
            </method>
            <trans-attribute>Required</trans-attribute>
        </container-transaction>
    </assembly-descriptor>
</ejb-jar>
