=== InveO/SharePlot/SharePlot/xml/META-INF/jet_finder2.dtd
<!ENTITY % Formula "CDATA">
<!--
A FINDERBODY:
  sql:	A boolean value where true indicates an sql string
  sql_string: 	The SQL Statement for the finder.
-->
<!ATTLIST FINDERBODY
	type (sql | nosql) "nosql"
	sql_string CDATA ""
	buffersize CDATA ""
>
<!ELEMENT FINDERBODY EMPTY>
<!--
A INPUT:
   name         is the name of the table inside the java enabling tool  (used i.e. in MAPPING element). 
   type		is the type of the input
-->
<!ATTLIST INPUT
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	localizedDisplayableText CDATA ""
>
<!ELEMENT INPUT EMPTY>
<!--
A view:
   name         is the name of this finder
-->
<!ATTLIST FINDER
	name CDATA #REQUIRED
>
<!ELEMENT FINDER (INPUT*, FINDERBODY)>
<!--
A Bean:
   name          is the ejb-name of the nut
-->
<!ATTLIST BEAN
	name CDATA #REQUIRED
>
<!ELEMENT BEAN (FINDER)*>
<!ELEMENT JET-FINDERS (BEAN)*>

=== InveO/SharePlot/SharePlot/xml/META-INF/FINDERS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JET-FINDERS SYSTEM "jet_finder2.dtd">
<JET-FINDERS>
    <BEAN name="Portfolio">
        <FINDER name="findAll">
            <FINDERBODY type="sql" sql_string="" buffersize="-1"/>
        </FINDER>
        <FINDER name="findByPreparedSQLQuery">
            <INPUT name="sqlWhereClause" type="String" localizedDisplayableText=""/>
            <INPUT name="sqlArguments" type="Object[]" localizedDisplayableText=""/>
            <FINDERBODY type="sql" sql_string="where @@@_SQL" buffersize="-1"/>
        </FINDER>
    </BEAN>
    <BEAN name="Share">
        <FINDER name="findAll">
            <FINDERBODY type="sql" sql_string="" buffersize="-1"/>
        </FINDER>
        <FINDER name="findByPreparedSQLQuery">
            <INPUT name="sqlWhereClause" type="String" localizedDisplayableText=""/>
            <INPUT name="sqlArguments" type="Object[]" localizedDisplayableText=""/>
            <FINDERBODY type="sql" sql_string="where @@@_SQL" buffersize="-1"/>
        </FINDER>
    </BEAN>
    <BEAN name="ShareQuantity">
        <FINDER name="findAll">
            <FINDERBODY type="sql" sql_string="" buffersize="-1"/>
        </FINDER>
        <FINDER name="findByShareAndPortfolio">
            <INPUT name="idPortfolio" type="Long" localizedDisplayableText=""/>
            <INPUT name="idShare" type="Long" localizedDisplayableText=""/>
            <FINDERBODY type="sql" sql_string="where idPortfolio = ? and idShare = ? order by valueDate asc" buffersize="-1"/>
        </FINDER>
        <FINDER name="findByPortfolio">
            <INPUT name="idPortfolio" type="Long" localizedDisplayableText=""/>
            <FINDERBODY type="sql" sql_string="where idPortfolio = ? order by valueDate asc" buffersize="-1"/>
        </FINDER>
        <FINDER name="findByPreparedSQLQuery">
            <INPUT name="sqlWhereClause" type="String" localizedDisplayableText=""/>
            <INPUT name="sqlArguments" type="Object[]" localizedDisplayableText=""/>
            <FINDERBODY type="sql" sql_string="where @@@_SQL" buffersize="-1"/>
        </FINDER>
    </BEAN>
    <BEAN name="ShareValue">
        <FINDER name="findAll">
            <FINDERBODY type="sql" sql_string="" buffersize="-1"/>
        </FINDER>
        <FINDER name="findByShare">
            <INPUT name="idShare" type="Long" localizedDisplayableText=""/>
            <FINDERBODY type="sql" sql_string="where idShare = ? order by valueDate asc" buffersize="-1"/>
        </FINDER>
        <FINDER name="findByShareAndDate">
            <INPUT name="idShare" type="Long" localizedDisplayableText=""/>
            <INPUT name="valueDate" type="java.util.Date" localizedDisplayableText=""/>
            <FINDERBODY type="sql" sql_string="where idShare = ? and valueDate &lt;= ? order by valueDate desc limit 1" buffersize="-1"/>
        </FINDER>
        <FINDER name="findByPreparedSQLQuery">
            <INPUT name="sqlWhereClause" type="String" localizedDisplayableText=""/>
            <INPUT name="sqlArguments" type="Object[]" localizedDisplayableText=""/>
            <FINDERBODY type="sql" sql_string="where @@@_SQL" buffersize="-1"/>
        </FINDER>
    </BEAN>
</JET-FINDERS>
