=== InveO/SharePlot/SharePlot/xml/metadata/datamodel/datamodel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT DATAMODEL (NODE+)>
<!ATTLIST DATAMODEL
    name NMTOKEN #REQUIRED
    serialuid CDATA #REQUIRED
>
<!ELEMENT NODE EMPTY>
<!ATTLIST NODE
    name NMTOKEN #REQUIRED
    type CDATA #REQUIRED
    nullable (true | false) #REQUIRED
    autoincrement (true | false) #REQUIRED
    length CDATA #REQUIRED
    pk (true | false) #REQUIRED
>

=== InveO/SharePlot/SharePlot/xml/metadata/datamodel/dm_Share.xml
<?xml version="1.0"?>
<!DOCTYPE DATAMODEL SYSTEM "datamodel.dtd">
<!-- The DATAMODEL serves as a template for building Models in the Application.
    To ensure that these models correspond to a specification and will therefore 
    be able to be written back to a persistence layer.
    
    Generated by JetTools, do not edit this file directly.
    
    The name of the DataModel will be used to register the definition in a global 
    registry.  -->
<DATAMODEL name="Share" serialuid="1750601616L" >
    <!-- NODE 
        type : Java type for the node value
        name : Name the node is to be given
     -->
    <NODE type="Long" name="idShare" nullable="false" autoincrement="true" length="10" />
    <NODE type="Long" name="idPortfolio" nullable="false" autoincrement="false" length="10" />
    <NODE type="String" name="name" nullable="false" autoincrement="false" length="255" />
    <NODE type="String" name="description" nullable="true" autoincrement="false" length="4000" />
    <NODE type="String" name="code" nullable="true" autoincrement="false" length="45" />
    <NODE type="java.util.Date" name="datePurchase" nullable="false" autoincrement="false" length="10" />
    <NODE type="java.math.BigDecimal" name="purchasePrice" nullable="false" autoincrement="false" length="12" />
    <NODE type="java.math.BigDecimal" name="entryFee" nullable="true" autoincrement="false" length="12" />
</DATAMODEL>

=== InveO/SharePlot/SharePlot/xml/metadata/datamodel/dm_ShareQuantity.xml
<?xml version="1.0"?>
<!DOCTYPE DATAMODEL SYSTEM "datamodel.dtd">
<!-- The DATAMODEL serves as a template for building Models in the Application.
    To ensure that these models correspond to a specification and will therefore
    be able to be written back to a persistence layer.

    Generated by JetTools, do not edit this file directly.

    The name of the DataModel will be used to register the definition in a global
    registry.  -->
<DATAMODEL name="ShareQuantity" serialuid="1077646545L" >
    <!-- NODE
        type : Java type for the node value
        name : Name the node is to be given
     -->
    <NODE type="Long" name="idShareQuantity" nullable="false" autoincrement="true" length="10" pk="true" />
    <NODE type="java.math.BigDecimal" name="changeFee" nullable="false" autoincrement="false" length="12" pk="false" />
    <NODE type="java.math.BigDecimal" name="changeQuantity" nullable="false" autoincrement="false" length="12" pk="false" />
    <NODE type="String" name="changeType" nullable="false" autoincrement="false" length="1" pk="false" />
    <NODE type="java.math.BigDecimal" name="changeValue" nullable="false" autoincrement="false" length="12" pk="false" />
    <NODE type="String" name="description" nullable="true" autoincrement="false" length="1000" pk="false" />
    <NODE type="Long" name="idShare" nullable="false" autoincrement="false" length="10" pk="false" />
    <NODE type="java.util.Date" name="valueDate" nullable="false" autoincrement="false" length="10" pk="false" />
</DATAMODEL>

=== InveO/SharePlot/SharePlot/xml/metadata/datamodel/portfolio/PortfolioShare.xml
<?xml version="1.0"?>
<!DOCTYPE DATAMODEL SYSTEM "datamodel.dtd">
<!-- The DATAMODEL serves as a template for building Models in the Application.
    To ensure that these models correspond to a specification and will therefore
    be able to be written back to a persistence layer.

    Generated by JetTools, do not edit this file directly.

    The name of the DataModel will be used to register the definition in a global
    registry.  -->
<DATAMODEL name="PortfolioShare" serialuid="1L" persist="false" >
    <!-- NODE
        type : Java type for the node value
        name : Name the node is to be given
     -->
    <NODE type="Long" name="idPortfolio" nullable="false" autoincrement="false" length="10" pk="true" default="" />
    <NODE type="String" name="portfolioName" nullable="false" autoincrement="false" length="45" pk="false" default="" />
    <NODE type="Long" name="idShare" nullable="false" autoincrement="false" length="10" pk="true" default="" />
    <NODE type="String" name="shareName" nullable="false" autoincrement="false" length="255" pk="false" default="" />
    <NODE type="java.util.Date" name="valueDate" nullable="false" autoincrement="false" length="10" pk="false" default="" />
    <NODE type="java.math.BigDecimal" name="changeQuantity" nullable="false" autoincrement="false" length="12" pk="false" default="" />
    <NODE type="java.math.BigDecimal" name="value" nullable="false" autoincrement="false" length="12" pk="false" default="" />
    <NODE type="java.math.BigDecimal" name="totalQuantity" nullable="false" autoincrement="false" length="12" pk="false" default="" />
</DATAMODEL>
