=== InveO/SharePlot/SharePlot/xml/databases/database2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 NT (http://www.xmlspy.com)-->
<!ELEMENT COLUMN EMPTY>
<!ATTLIST COLUMN
	name CDATA  #REQUIRED
	localname CDATA  #REQUIRED
	dbtype (VARCHAR | VARCHAR2 | DATE | INTEGER | DOUBLE | CHAR | SMALLINT | TIMESTAMP | TIME | REAL | BIGINT | BIT | OBJECT | DECIMAL | BLOB ) #REQUIRED
>
<!ELEMENT DATABASE (TABLE+, DBTYPES?)>
<!--
A Database:
   name          is the name of the view inside the Java Enabling Tool (used i.e. in TABLE element). 
   databasename  is the name of the database inside the DBMS.
   user          is the name of the default user for accessing this database.
   password      is the password corresponding to the user.
   type          defines the DBMS used (DB2, ORACLE, ...)
   driver        is the driver to use for this database 
-->
<!ATTLIST DATABASE
	name CDATA #REQUIRED
>
<!-- !ATTLIST DATABASE
	databasename CDATA #REQUIRED
	user CDATA #REQUIRED
	password CDATA #REQUIRED
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	driverJar CDATA #REQUIRED
	driver CDATA #REQUIRED
	jndidatasource CDATA #REQUIRED
-->
<!ELEMENT DBTYPE EMPTY>
<!--
TO BE REMOVED do not use
-->
<!ATTLIST DBTYPE
	dbtype (VARCHAR | VARCHAR2 | DATE | INTEGER | DOUBLE | CHAR | SMALLINT | TIMESTAMP | TIME | REAL | BIGINT | BIT | OBJECT | DECIMAL ) #REQUIRED
	java-type (Boolean | Byte | Char | Date | Double | Float | Integer | Long | Object | Short | String | boolean | byte | char | double | float | int | long | short | java.math.BigDecimal | java.util.Date ) #REQUIRED
>
<!ELEMENT DBTYPES (DBTYPE+)>
<!ATTLIST DBTYPES
	descriptif CDATA #REQUIRED
>
<!ELEMENT TABLE (COLUMN+)>
<!--
A database table:
   name    is the name of the table inside the Java Enabling Tool (used i.e. in MAPPING element). 
   localname         refers to a DATABASE element.
-->
<!ATTLIST TABLE
	name CDATA  #REQUIRED
	localname CDATA  #REQUIRED
>

=== InveO/SharePlot/SharePlot/xml/databases/DataBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DATABASE SYSTEM "database2.dtd">
<!-- 
    Warning : The Column name must match the name of the field in the java classes

-->
<DATABASE name="SharePlot" >
    <TABLE name="Portfolio" localname="Portfolio">
        <COLUMN name="idPortfolio" localname="idPortfolio" dbtype="INTEGER"/>
        <COLUMN name="isFake" localname="isFake" dbtype="CHAR"/>
        <COLUMN name="name" localname="name" dbtype="VARCHAR"/>
    </TABLE>
    <TABLE name="Share" localname="Share">
        <COLUMN name="idShare" localname="idShare" dbtype="INTEGER"/>
        <COLUMN name="codeISIN" localname="codeISIN" dbtype="VARCHAR"/>
        <COLUMN name="codeYahoo" localname="codeYahoo" dbtype="VARCHAR"/>
        <COLUMN name="description" localname="description" dbtype="VARCHAR"/>
        <COLUMN name="name" localname="name" dbtype="VARCHAR"/>
    </TABLE>
    <TABLE name="ShareQuantity" localname="ShareQuantity">
        <COLUMN name="idShareQuantity" localname="idShareQuantity" dbtype="INTEGER"/>
        <COLUMN name="changeFee" localname="changeFee" dbtype="DECIMAL"/>
        <COLUMN name="changeQuantity" localname="changeQuantity" dbtype="DECIMAL"/>
        <COLUMN name="changeType" localname="changeType" dbtype="CHAR"/>
        <COLUMN name="changeValue" localname="changeValue" dbtype="DECIMAL"/>
        <COLUMN name="description" localname="description" dbtype="VARCHAR"/>
        <COLUMN name="idPortfolio" localname="idPortfolio" dbtype="INTEGER"/>
        <COLUMN name="idShare" localname="idShare" dbtype="INTEGER"/>
        <COLUMN name="totalQuantity" localname="totalQuantity" dbtype="DECIMAL"/>
        <COLUMN name="valueDate" localname="valueDate" dbtype="DATE"/>
    </TABLE>
    <TABLE name="ShareValue" localname="ShareValue">
        <COLUMN name="idShareValue" localname="idShareValue" dbtype="INTEGER"/>
        <COLUMN name="idShare" localname="idShare" dbtype="INTEGER"/>
        <COLUMN name="value" localname="value" dbtype="DECIMAL"/>
        <COLUMN name="valueDate" localname="valueDate" dbtype="DATE"/>
    </TABLE>
    <!--DBTYPES descriptif="">
        <DBTYPE dbtype="VARCHAR" java-type="String"/>
        <DBTYPE dbtype="BIT" java-type="Boolean"/>
        <DBTYPE dbtype="BIT" java-type="boolean"/>
        <DBTYPE dbtype="SMALLINT" java-type="Byte"/>
        <DBTYPE dbtype="INTEGER" java-type="Integer"/>
        <DBTYPE dbtype="DOUBLE" java-type="Double"/>
        <DBTYPE dbtype="DATE" java-type="Date"/>
        <DBTYPE dbtype="DATE" java-type="java.util.Date"/>
        <DBTYPE dbtype="REAL" java-type="Float"/>
        <DBTYPE dbtype="BIGINT" java-type="Long"/>
        <DBTYPE dbtype="DECIMAL" java-type="java.math.BigDecimal"/>
        <DBTYPE dbtype="SMALLINT" java-type="Short"/>
        <DBTYPE dbtype="CHAR" java-type="Char"/>
        <DBTYPE dbtype="SMALLINT" java-type="byte"/>
        <DBTYPE dbtype="INTEGER" java-type="int"/>
        <DBTYPE dbtype="DOUBLE" java-type="double"/>
        <DBTYPE dbtype="REAL" java-type="float"/>
        <DBTYPE dbtype="BIGINT" java-type="long"/>
        <DBTYPE dbtype="SMALLINT" java-type="short"/>
        <DBTYPE dbtype="CHAR" java-type="char"/>
        <DBTYPE dbtype="OBJECT" java-type="Object"/>
    </DBTYPES-->
</DATABASE>
