=== InveO/SharePlot/SharePlot/xml/metadata/datasourceexecutor/datasourceexecutor.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated from dse_AccountPlanStruct.xml by XMLBuddy -->
<!ELEMENT EJB EMPTY>
<!ATTLIST EJB name NMTOKEN #REQUIRED>
<!ELEMENT EJB_CONVERSION (MAPPING+)>
<!ATTLIST EJB_CONVERSION datamodel NMTOKEN #REQUIRED>
<!ELEMENT EJB_FINDERS (EJB,FINDER+,EJB_CONVERSION)>
<!ELEMENT FINDER (INPUT*)>
<!ATTLIST FINDER
    name NMTOKEN #REQUIRED
    primarykey (true | false) "false"
>
<!ELEMENT INPUT EMPTY>
<!ATTLIST INPUT
    dataconverter CDATA #REQUIRED
    source NMTOKEN #REQUIRED
    subelement CDATA #REQUIRED
>
<!ELEMENT MAPPING EMPTY>
<!ATTLIST MAPPING
    autoincrement (true | false) "false"
    primarykey (true | false) "false"
    default CDATA #FIXED ""
    defaulttype (INTEGER | TEXT | DATE | DOUBLE | BLOB ) "TEXT"
    name NMTOKEN #REQUIRED
    readconverter CDATA #FIXED ""
    readmultikey CDATA #FIXED ""
    subelement CDATA #FIXED ""
    target NMTOKEN #REQUIRED
    writeconverter CDATA #FIXED ""
>

=== InveO/SharePlot/SharePlot/xml/metadata/datasourceexecutor/dse_Portfolio.xml
<?xml version="1.0"?>
<!DOCTYPE EJB_FINDERS SYSTEM "datasourceexecutor.dtd">
<!-- 
    Generated by JetTools, do not edit this file directly.
    -->
<EJB_FINDERS>
    <!-- EJB : This simply links this to the name of the corresponding EJB -->
    <EJB name="Portfolio"/>
    
    <!-- FINDER : This will detail the various finders available in the EJB.
             name : name of the finder in the EJB layer
             primarykey : is this the find by PK method, in which case the arguments will be wrapped in the PK object
     -->
    <!-- INPUT : This will describe each input argument and how it must be converted befor being passed on to the ejb layer
            dataconverter : converter name
            subelement : in case the converter returns several elements, this selects the appropriate one
            source : name of the item in the data model
     -->
    <FINDER primarykey="false" name="findAll">
    </FINDER>
    <FINDER primarykey="false" name="findByPreparedSQLQuery">
        <INPUT dataconverter="" subelement="" source="sqlWhereClause"/>
        <INPUT dataconverter="" subelement="" source="sqlArguments"/>
    </FINDER>
    <FINDER primarykey="true" name="findByPrimaryKey">
        <INPUT dataconverter="" subelement="" source="idPortfolio"/>
    </FINDER>
    
    <!-- EJB_CONVERSION : Details the mapping between the Bean and the DataModel
            datamodel : name of the associated data model structure
     -->
    <EJB_CONVERSION datamodel="Portfolio">
        <!-- MAPPING
            writeconverter : data converter to use when writing to the EJB
            readmultikey : not used yet
            defaulttype : Object typr for the default value
            target : name of the node in the data model
            subelement : not used yet
            default : default value
            readconverter : dataconverter to use when reading from the EJB
            name : name of the corresonding accessor in the Bean (ie : if name == "myField" the accessor used will be getMyField())
            autoincrement : "true" if the field is set as autoincrement in the database, at the moment this is only valid on a PK field (unique)
            primarykey : "true" if the field is part of the primary key (it will not be updateable)
         -->
        <MAPPING writeconverter="" readmultikey="" defaulttype="INTEGER" target="idPortfolio" subelement="" default="" readconverter="" name="idPortfolio" autoincrement="true" primarykey="true" />
        <MAPPING writeconverter="" readmultikey="" defaulttype="TEXT" target="isFake" subelement="" default="" readconverter="" name="isFake" autoincrement="false" primarykey="false" />
        <MAPPING writeconverter="" readmultikey="" defaulttype="TEXT" target="name" subelement="" default="" readconverter="" name="name" autoincrement="false" primarykey="false" />
    </EJB_CONVERSION>
</EJB_FINDERS>
